### ISSUE TITLE
本番環境：brank=True,null=Trueでもなぜかherokuのデータベース(PostgreSQL)で追加カラムがない、と言われる

### ISSUE THREAD

**Issue by shin-carpediem** [shin-carpediem/Atom#7]
aokishinichiro@MacBook-Pro-2 Atom % heroku run python manage.py migrate
Running python manage.py migrate on ⬢ atom-production... up, run.9674 (Free)
/app/.heroku/python/lib/python3.7/site-packages/environ/environ.py:639: UserWarning: Error reading .env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)
Operations to perform:
  Apply all migrations: admin, app, auth, contenttypes, guardian, sessions, social_django, users
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column users_user.house_common_fee does not exist
LINE 1: ...l", "users_user"."name", "users_user"."house_id", "users_use...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 256, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/sql.py", line 50, in emit_post_migrate_signal
    **kwargs
  File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/app/.heroku/python/lib/python3.7/site-packages/guardian/management/__init__.py", line 32, in create_anonymous_user
    User.objects.using(kwargs['using']).get(**lookup)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column users_user.house_common_fee does not exist
LINE 1: ...l", "users_user"."name", "users_user"."house_id", "users_use...
                                                             ^

**Comment by shin-carpediem** [comment]
heroku postgreに接続して直接カラムを追加して解決。

**Comment by shin-carpediem** [comment]
この事から、migrationファイルがheroku用に正しく作られていない事がわかった。
